name: quick_notes
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.3.4
  go_router: ^13.2.0
  build_runner: ^2.4.8

dev_dependencies:
  custom_lint: ^0.6.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true
